apiVersion: v1
kind: ConfigMap
metadata:
  name: site-comemorativo-config
  labels:
    app: site-comemorativo
data:
  NODE_ENV: "production"
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
  NEXT_PUBLIC_BASE_PATH: "/site-comemorativo"
