apiVersion: v1
kind: Service
metadata:
  name: atendimento-app
  labels:
    app: atendimento-app
spec:
  type: ClusterIP
  selector:
    app: atendimento-app
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
