apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-app
  labels:
    app: management-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: management-app
  template:
    metadata:
      labels:
        app: management-app
    spec:
      containers:
        - name: management-app
          image: management-app:unpublished
          imagePullPolicy: IfNotPresent
