apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-kube-linter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-kube-linter
  template:
    metadata:
      labels:
        app: test-kube-linter
    spec:
      containers:
        - name: app
          image: nginx:latest
