apiVersion: v1
kind: Service
metadata:
  name: atendimento
  labels:
    app: atendimento
spec:
  type: ClusterIP
  selector:
    app: atendimento
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
