apiVersion: v1
kind: Service
metadata:
  name: gestao-escolar-frontend
  labels:
    app: gestao-escolar-frontend
spec:
  type: ClusterIP
  selector:
    app: gestao-escolar-frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP