apiVersion: apps/v1
kind: Deployment
metadata:
  name: apae
  labels:
    app: apae
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apae
  template:
    metadata:
      labels:
        app: apae
    spec:
      containers:
        - name: apae
          image: ghcr.io/ifpbesp/apae-geral-frontend:dev
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 3000
              protocol: TCP

          envFrom:
            - configMapRef:
                name: apae-config

          startupProbe:
            httpGet:
              path: /apae-geral
              port: http
            periodSeconds: 5
            failureThreshold: 12

          readinessProbe:
            httpGet:
              path: /apae-geral
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /apae-geral
              port: http
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

          securityContext:
            runAsUser: 65532
            runAsGroup: 65532

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
