apiVersion: v1
kind: Service
metadata:
  name: apae
  labels:
    app: apae
spec:
  type: ClusterIP
  selector:
    app: apae
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP